version: '3'
services:
  node:
    build:
      context: server
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - '8080:8080'
    volumes:
      - './server:/usr/src/app'
      - './client:/usr/src/app/client'
  mongo:
    image: mongo
    
  angular:
    build:
      context: client
    working_dir: /usr/src/app
    ports:
      - '8081:8081'
    volumes: 
      - './client:/usr/src/app'
    